import { Project } from "@/types/project";

export const fallbackProjects: Project[] = [
    {
        _id: "p1",
        title: "Caneza",
        slug: "caneza",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b66344bf83f6c336dff784",
        isFeatured: true,
        order: 1,
        tools: ["AI Filmmaking", "Gen-3"],
        brief: "Cinematic AI sequence for Caneza.",
        approach: "Text-to-video refinement."
    },
    {
        _id: "p2",
        title: "Melting Rock",
        slug: "melting-rock",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b66344c8f901eb750ba477",
        isFeatured: true,
        order: 2,
        tools: ["AI Filmmaking", "Fluid Dynamics"],
        brief: "Dynamic AI simulation for Melting Rock.",
        approach: "Neural physics rendering."
    },
    {
        _id: "p3",
        title: "Beyond Glass",
        slug: "beyond-glass",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b66344dc37184fc7ace603",
        isFeatured: true,
        order: 3,
        tools: ["AI Filmmaking", "Cinematic AI"],
        brief: "Experimental AI visuals for Beyond Glass.",
        approach: "Latent space exploration."
    },
    {
        _id: "p4",
        title: "Kimirica One",
        slug: "kimirica-one",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b66344dc37184fc7ace601",
        isFeatured: true,
        order: 4,
        tools: ["AI Filmmaking", "Upscaling"],
        brief: "High-fidelity AI sequence for Kimirica One.",
        approach: "Enhanced visual storytelling."
    },
    {
        _id: "p5",
        title: "Swiss Beauty",
        slug: "swiss-beauty",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b679f7dc37184fc7ae6a87",
        isFeatured: true,
        order: 5,
        tools: ["AI Filmmaking", "Aesthetics"],
        brief: "Premium AI sequence for Swiss Beauty.",
        approach: "High-contrast visual design."
    },
    {
        _id: "p6",
        title: "Super maka teaser",
        slug: "super-maka-teaser",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b66344c8f901eb750ba475",
        isFeatured: true,
        order: 6,
        tools: ["AI Filmmaking", "Teaser"],
        brief: "Conceptual AI teaser for Super maka.",
        approach: "Atmospheric world building."
    }
];
