import { Project } from "@/types/project";

export const fallbackProjects: Project[] = [
    {
        _id: "p4",
        title: "Caneza",
        slug: "project-4",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3bf83f6c336c678cb",
        isFeatured: true,
        order: 4,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Caneza.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p5",
        title: "Kimirica one",
        slug: "project-5",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3bf83f6c336c678ec",
        isFeatured: true,
        order: 5,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Kimirica one.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p6",
        title: "Kimirica Precise Speed",
        slug: "project-6",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3dc37184fc7936dde",
        isFeatured: true,
        order: 6,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Kimirica Precise Speed.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p7",
        title: "Meet Bhaskar Anna!",
        slug: "project-7",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3c8f901eb75f225a0",
        isFeatured: true,
        order: 7,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Meet Bhaskar Anna!.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p8",
        title: "Melting clock",
        slug: "project-8",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3dc37184fc7936dd9",
        isFeatured: true,
        order: 8,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Melting clock.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p9",
        title: "Oneshot",
        slug: "project-9",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3c8f901eb75f22598",
        isFeatured: true,
        order: 9,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Oneshot.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p10",
        title: "Shadows",
        slug: "project-10",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3c8f901eb75f2257a",
        isFeatured: true,
        order: 10,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Shadows.",
        approach: "Utilized custom generative models."
    },
    {
        _id: "p11",
        title: "Super maka teaser",
        slug: "project-11",
        client: "Client Work",
        role: "Director",
        year: "2024",
        categoryId: "c1",
        categoryTitle: "Selected Works",
        thumbnailUrl: "",
        videoType: "external",
        gumletId: "69b4fad3dc37184fc7936de1",
        isFeatured: true,
        order: 11,
        tools: ["AI Filmmaking"],
        brief: "AI generated sequence for Super maka teaser.",
        approach: "Utilized custom generative models."
    }
];
